import type { Role } from '../types/election';

export const HAS_PERMISSION = {
  CAST_VOTE: ['VOTER'],
  MANAGE_ELECTION: ['ADMIN'],
  MANAGE_USERS: ['ADMIN'],
  MANAGE_REGIONS: ['ADMIN'],
  MANAGE_DISTRICTS: ['ADMIN', 'REGIONAL_ADMIN'],
  MANAGE_POLLING_STATIONS: ['ADMIN', 'REGIONAL_ADMIN', 'DISTRICT_ADMIN'],
  VIEW_AUDIT_LOGS: ['ADMIN'],
  VIEW_REGIONAL_STATS: ['ADMIN', 'REGIONAL_ADMIN'],
  MANAGE_DISTRICT_OPERATIONS: ['ADMIN', 'REGIONAL_ADMIN'],
  VIEW_DISTRICT_STATS: ['ADMIN', 'REGIONAL_ADMIN', 'DISTRICT_ADMIN'],
  MANAGE_STAFF: ['ADMIN', 'DISTRICT_ADMIN'],
  REGISTER_VOTER: ['ADMIN', 'STAFF', 'REGIONAL_ADMIN', 'DISTRICT_ADMIN'],
  VIEW_VOTERS: ['ADMIN', 'STAFF', 'REGIONAL_ADMIN', 'DISTRICT_ADMIN'],
  VIEW_RESULTS: ['ADMIN', 'REGIONAL_ADMIN', 'DISTRICT_ADMIN', 'STAFF', 'OBSERVER'],
  MONITOR_ELECTION: ['ADMIN', 'REGIONAL_ADMIN', 'DISTRICT_ADMIN', 'OBSERVER'],
} as const satisfies Record<string, readonly Role[]>;

export const checkPerm = (role: Role, permission: keyof typeof HAS_PERMISSION) =>
  HAS_PERMISSION[permission].includes(role);
